package com.cbrc.tokens.keywords;

import java.util.Stack;

import com.cbrc.base.Token;
import com.cbrc.lexers.structs.TokenizedCode;
import com.cbrc.tokens.KeywordToken;

public class DoWhileKeywordToken extends KeywordToken {

	public DoWhileKeywordToken() {
		super("do while");
	}

	/**
	 * Note: This is never used, because DoWhileKeywordToken is a special
	 * token generated by the parser and not the lexer.
	 */
	@Override
	public Token generateCondition(String token, TokenizedCode tokens,
			Stack<String> currentMarker, String succeedingToken) {
		return null;
	}

	@Override
	protected String getAdditionalDetails() {
		return "Do While statement";
	}

}
